# Generated by Django 6.1.1 on 2026-10-04 07:03

import wagtail_daisIE.allauth_emails.catalogue
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllauthEmailOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_prefix', models.CharField(choices=wagtail_daisIE.allauth_emails.catalogue.get_allauth_email_choices, help_text='The allauth email event to override.', max_length=255, unique=True, verbose_name='Allauth email')),
                ('is_active', models.BooleanField(default=False, help_text='Only active overrides are used.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Allauth email override',
                'verbose_name_plural': 'Allauth email overrides',
                'ordering': ['template_prefix'],
            },
        ),
    ]
