# Generated by Django 6.1.1 on 2026-10-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtail_daisIE_allauth_emails', '0001_initial'),
        ('wagtail_daisIE_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allauthemailoverride',
            name='email_template',
            field=models.ForeignKey(blank=True, help_text="Leave empty to use allauth's default templates.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE_notifications.emailtemplate', verbose_name='Email template'),
        ),
    ]
