# Generated by Django 6.1.1 on 2026-10-04 07:03

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail_daisIE.pages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtail_daisIE', '0001_initial'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='blogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpage'),
        ),
        migrations.AddField(
            model_name='blogpagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='blogpersonrelationship',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_person_relationship', to='blog.blogpage'),
        ),
        migrations.AddField(
            model_name='bread',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='breaddetailpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='breaddetailpage',
            name='design_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Shared design page'),
        ),
        migrations.AddField(
            model_name='breaddetailpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='breaddetailpage',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Source model'),
        ),
        migrations.AddField(
            model_name='breaddetailtemplate',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='breaddetailtemplate',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='breaddetailtemplate',
            name='parent_page',
            field=models.ForeignKey(blank=True, help_text='Where pages generated for this detail type are added.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Generated pages live under'),
        ),
        migrations.AddField(
            model_name='breadindexpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='breadindexpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='breadsuggestion',
            name='bread',
            field=models.ForeignKey(blank=True, help_text='The bread created from this suggestion once approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.bread', verbose_name='Bread'),
        ),
        migrations.AddField(
            model_name='breadsuggestionformpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='breadsuggestionformpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='breadsuggestionformpage',
            name='success_redirect_page',
            field=models.ForeignKey(blank=True, help_text='Redirect here after a successful submission instead of the body.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Success redirect'),
        ),
        migrations.AddField(
            model_name='breadsuggestionformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='blog.breadsuggestionformpage'),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='person',
            name='latest_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision'),
        ),
        migrations.AddField(
            model_name='person',
            name='live_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision'),
        ),
        migrations.AddField(
            model_name='blogpersonrelationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_blog_relationship', to='blog.person'),
        ),
        migrations.AddConstraint(
            model_name='breaddetailpage',
            constraint=models.UniqueConstraint(fields=('detail_key', 'source_content_type', 'source_object_id'), name='blog_breaddetailpage_unique_detail_source'),
        ),
    ]
