# Generated by Django 6.1.1 on 2026-10-04 19:58

import wagtail_daisIE.forms.registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadsuggestionformfield',
            name='field_type',
            field=models.CharField(choices=wagtail_daisIE.forms.registry.get_form_field_type_choices, max_length=16, verbose_name='field type'),
        ),
    ]
