# Generated by Django 6.1.1 on 2026-10-04 07:03

import django.db.models.deletion
import wagtail_daisIE.pages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('wagtail_daisIE', '0001_initial'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demopage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
    ]
