# Generated by Django 6.1.1 on 2026-10-05 18:29

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.models.preview
import wagtail_daisIE.base_blocks.audience
import wagtail_daisIE.notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtail_daisIE', '0001_initial'),
        ('wagtailcore', '0098_apitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('kind', models.CharField(choices=wagtail_daisIE.notifications.models.audience_kind_choices, default='manual', max_length=10, verbose_name='Type')),
                ('rule_key', models.CharField(blank=True, choices=wagtail_daisIE.base_blocks.audience.get_audience_rule_choices, help_text='The settings audience rule to source users from.', max_length=64, verbose_name='Audience rule')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Audience',
                'verbose_name_plural': 'Audiences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('name', models.CharField(help_text='A unique name used to identify this template, e.g. "Welcome email".', max_length=255, unique=True, verbose_name='Name')),
                ('template_key', models.CharField(blank=True, help_text='Optional stable key used to bind this template to a bridge or integration (e.g. an allauth email prefix).', max_length=255, null=True, unique=True, verbose_name='Template key')),
                ('subject', models.CharField(blank=True, default='', help_text='Stored as the MJML title, e.g. for the email subject line.', max_length=255, verbose_name='Subject')),
                ('preheader', models.CharField(blank=True, default='', help_text='Short preview text shown by email clients after the subject.', max_length=255, verbose_name='Preheader')),
                ('design', wagtail.fields.StreamField([('defaults', 0)], blank=True, block_lookup={0: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.PageDesignBlock'], {})}, help_text='Default container, text, button and media styles applied to every block in this email. Per-block settings are applied on top.', verbose_name='Default design')),
                ('content', wagtail.fields.StreamField([('section', 0), ('wrapper', 1), ('hero', 2), ('raw', 3)], blank=True, block_lookup={0: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.EmailSectionBlock'], {}), 1: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.EmailWrapperBlock'], {}), 2: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.EmailHeroBlock'], {}), 3: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.EmailRawBlock'], {})}, help_text='Add MJML components to build the email body.', verbose_name='Email content')),
                ('email_theme', models.ForeignKey(blank=True, help_text='Theme applied to this email. Falls back to the default theme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme', verbose_name='Email theme')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('status', models.CharField(choices=wagtail_daisIE.notifications.models.campaign_status_choices, default='draft', max_length=16, verbose_name='Status')),
                ('send_mode', models.CharField(choices=wagtail_daisIE.notifications.models.campaign_send_mode_choices, default='manual', max_length=10, verbose_name='Send mode')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Used when the send mode is scheduled.', null=True, verbose_name='Scheduled at')),
                ('recurrence', models.CharField(choices=wagtail_daisIE.notifications.models.campaign_recurrence_choices, default='none', max_length=10, verbose_name='Repeat')),
                ('context', wagtail.fields.StreamField([('variable', 0)], blank=True, block_lookup={0: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.EmailVariableBlock'], {})}, help_text='Extra values exposed as {{ payload.<name> }}.', verbose_name='Variables')),
                ('last_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0, editable=False)),
                ('failed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='wagtail_daisIE_notifications.audience', verbose_name='Audience')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_daisIE_notifications.emailtemplate', verbose_name='Email template')),
            ],
            options={
                'verbose_name': 'Email campaign',
                'verbose_name_plural': 'Email campaigns',
                'ordering': ['-scheduled_at', 'name'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AudienceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('audience', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='wagtail_daisIE_notifications.audience')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audience member',
                'verbose_name_plural': 'Audience members',
                'ordering': ['sort_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='wagtail_daisIE.audience_member_target'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('audience', 'user'), name='wagtail_daisIE.unique_audience_user'), models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('audience', 'email'), name='wagtail_daisIE.unique_audience_email')],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=wagtail_daisIE.notifications.models.campaign_log_status_choices, default='sent', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='wagtail_daisIE_notifications.emailcampaign')),
            ],
            options={
                'verbose_name': 'Campaign recipient log',
                'verbose_name_plural': 'Campaign recipient logs',
                'constraints': [models.UniqueConstraint(fields=('campaign', 'recipient_email'), name='wagtail_daisIE.unique_campaign_recipient')],
            },
        ),
    ]
