# Generated by Django 6.1.1 on 2026-10-04 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtail_daisIE', '0001_initial'),
        ('wagtail_daisIE_allauth_ui', '0001_initial'),
        ('wagtail_daisIE_menus', '0001_initial'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='allauthpageoverride',
            name='footer_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE_menus.daisyuimenu', verbose_name='Footer menu'),
        ),
        migrations.AddField(
            model_name='allauthpageoverride',
            name='header_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE_menus.daisyuimenu', verbose_name='Header menu'),
        ),
        migrations.AddField(
            model_name='allauthpageoverride',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Leave empty to use this as the global fallback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='allauthpageoverride',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Theme used to style this page. Falls back to the default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme', verbose_name='Theme'),
        ),
    ]
