"""Generate the Tailwind safelist from the package's class choices.

The design system builds class strings at runtime (``block_css``), so Tailwind
cannot discover them by scanning templates. Every class an editor can choose is
declared in :mod:`wagtail_daisIE.choices`; this command turns those choices into
``@source inline(...)`` directives in ``tailwind/safelist.css``, which the
committed ``daisie.css`` is built from.
"""

from __future__ import annotations

from pathlib import Path

from django.core.management.base import BaseCommand

from wagtail_daisIE import choices


def _values(sequence):
    """Yield the stored value of every choice in ``sequence``."""
    for item in sequence or []:
        value = item[0] if isinstance(item, (tuple, list)) and item else item
        if isinstance(value, str) and value:
            yield value


class Command(BaseCommand):
    help = "Generate tailwind/safelist.css from the package's class choices."

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            default=None,
            help="Output path (defaults to the package tailwind/safelist.css).",
        )

    def handle(self, *args, **options):
        from wagtail_daisIE.dynamic import feeds

        classes = set()
        for name in choices.__all__:
            constant = getattr(choices, name, None)
            if isinstance(constant, (list, tuple)):
                classes.update(_values(constant))

        # Button states render with ``hover:``/``active:`` variants.
        button_values = set()
        for name in (
            "DAISYUI_BUTTON_COLOR_CHOICES",
            "DAISYUI_BUTTON_STYLE_CHOICES",
            "DAISYUI_BUTTON_SIZE_CHOICES",
            "DAISYUI_BUTTON_BEHAVIOR_CHOICES",
            "DAISYUI_BUTTON_MODIFIER_CHOICES",
        ):
            button_values.update(_values(getattr(choices, name, [])))
        for value in button_values:
            classes.add(value)
            classes.add(f"hover:{value}")
            classes.add(f"active:{value}")

        # Typography colour/decoration supports hover/active states.
        for name in (
            "DAISYUI_TEXT_COLOR_CHOICES",
            "TEXT_DECORATION_CHOICES",
            "DECORATION_COLOR_CHOICES",
            "DECORATION_THICKNESS_CHOICES",
        ):
            for value in _values(getattr(choices, name, [])):
                classes.add(value)
                classes.add(f"hover:{value}")
                classes.add(f"active:{value}")

        # Runtime-built layout classes (feed containers).
        for value in feeds.GRID_COLUMNS.values():
            classes.update(part for part in value.split() if part)

        classes.discard("None")
        classes.update({"daisie-feed__item"})

        lines = [
            "/* Generated by `manage.py daisie_safelist`. Do not edit by hand. */",
        ]
        lines.extend(f'@source inline("{value}");' for value in sorted(classes))

        output = options["output"]
        path = (
            Path(output)
            if output
            else Path(__file__).resolve().parents[2] / "tailwind" / "safelist.css"
        )
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {path} ({len(classes)} classes)"))
