# Generated by Django 6.1.1 on 2026-10-05 18:29

import django.db.models.deletion
import wagtail.fields
import wagtail.models.preview
import wagtail_daisIE.menus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtail_daisIE', '0001_initial'),
        ('wagtailcore', '0098_apitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaisyUIMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('name', models.CharField(help_text='A unique name used to render this menu in templates, e.g. {% daisyui_menu "Main navigation" %}.', max_length=255, unique=True, verbose_name='Name')),
                ('layout', models.CharField(choices=wagtail_daisIE.menus.models.menu_layout_choices, default='navbar', help_text='How the menu is rendered: a top navbar, a footer, a sidebar drawer, or a standalone horizontal/vertical list.', max_length=32, verbose_name='Layout')),
                ('branding', wagtail.fields.StreamField([('branding', 0)], blank=True, block_lookup={0: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.MenuBranding'], {})}, help_text='Logo and/or wordmark, optionally wrapped in a link.', verbose_name='Branding')),
                ('show_search', models.BooleanField(default=False, help_text='Display a search form in the navbar.', verbose_name='Show search box')),
                ('search_url', models.CharField(blank=True, default='/search/', help_text='URL the search form submits to.', max_length=255, verbose_name='Search URL')),
                ('search_parameter', models.CharField(blank=True, default='query', help_text='Query-string parameter used for the search term.', max_length=64, verbose_name='Search parameter')),
                ('search_placeholder', models.CharField(blank=True, default='Search', max_length=128, verbose_name='Search placeholder')),
                ('show_theme_toggle', models.BooleanField(default=False, help_text='Display a light/dark theme toggle in the navbar.', verbose_name='Show theme toggle')),
                ('menu_design', wagtail.fields.StreamField([('menu', 0)], blank=True, block_lookup={0: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.SpacedDesignBlock'], {})}, help_text='Styling for the menu container itself (background, padding, border, size). Kept separate from the menu item defaults below.', verbose_name='Menu design')),
                ('item_design', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.MenuItemDesignBlock'], {})}, help_text='Default font, colour, background and spacing applied to every item. Per-item settings are applied on top.', verbose_name='Menu item defaults')),
                ('sticky', models.BooleanField(default=False, help_text='Keep the navbar fixed to the top of the viewport.', verbose_name='Sticky navbar')),
                ('body', wagtail.fields.StreamField([('link', 0), ('button', 1), ('search', 2), ('inline_card', 3), ('accordion', 4), ('link_list', 5), ('header', 6), ('text', 7), ('action', 8), ('newsletter', 9)], blank=True, block_lookup={0: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.LabelLinkBlock'], {}), 1: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.ButtonBlock'], {}), 2: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.MenuSearchBoxBlock'], {}), 3: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.InlineCardBlock'], {}), 4: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.AccordionBlock'], {}), 5: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.LinkListBlock'], {}), 6: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.HeaderBlock'], {}), 7: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.InlineTextBlock'], {}), 8: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.ActionBlock'], {}), 9: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.MenuNewsletterBlock'], {})}, help_text='Add links, buttons, accordions and other menu components.', verbose_name='Menu items')),
                ('context_bindings', wagtail.fields.StreamField([('binding', 0)], blank=True, block_lookup={0: ('wagtail_daisIE.blockref.RegisteredBlock', ['wagtail_daisIE.ContextBindingBlock'], {})}, help_text="Expose context models to this menu's items, e.g. the current user.", verbose_name='Context bindings')),
                ('alt_menu_theme', models.ForeignKey(blank=True, help_text='Theme applied when the toggle is switched on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme', verbose_name='Alternate theme')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
                ('menu_theme', models.ForeignKey(blank=True, help_text='Theme applied to this menu. Falls back to the default theme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme', verbose_name='Menu theme')),
            ],
            options={
                'verbose_name': 'DaisyUI Menu',
                'verbose_name_plural': 'DaisyUI Menus',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
