"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "wagtail_daisIE",
    "blog",
    "home",
    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.routable_page",
    "wagtail.contrib.redirects",
    "wagtail.contrib.table_block",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "colorfield",
    "allauth",
    "allauth.account",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "demo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail_daisIE.icons.context_processors.icon_assets",
            ],
        },
    },
]

WSGI_APPLICATION = "demo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("DATABASE_NAME", BASE_DIR / "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "demo"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = [
    "csv",
    "docx",
    "key",
    "odt",
    "pdf",
    "pptx",
    "rtf",
    "txt",
    "xlsx",
    "zip",
]

# ---------------------------------------------------------------------------
# Wagtail DaisyUI Interface Editor demo configuration
# ---------------------------------------------------------------------------

SITE_ID = 1

# Context models: values authors can reference in content as {{ key.field }}.
WAGTAIL_DAISIE_CONTEXT_MODELS = {
    "user": {
        "label": "Current user",
        "model": "auth.User",
        "source": "request.user",
    },
    "blog_post": {
        "label": "Current blog post",
        "model": "blog.BlogPage",
        "source": "url",
        "lookup_field": "slug",
        "url_source": "get_absolute_url",
        "queryset": "blog.feed.live_posts",
        "filters": {
            "tag": {
                "label": "Tag",
                "type": "choice",
                "field": "tags__slug",
                "choices": "blog.filters.tags",
            },
            "author": {
                "label": "Author",
                "type": "choice",
                "multi": True,
                "field": "blog_person_relationship__person_id",
                "choices": "blog.filters.authors",
            },
            "published": {
                "label": "Published",
                "type": "date_range",
                "field": "date_published",
            },
        },
    },
    "bread_suggestion": {
        "label": "Bread suggestion",
        "model": "blog.BreadSuggestion",
        "source": "url",
        "lookup_field": "pk",
    },
    "bread": {
        "label": "Bread",
        "model": "blog.Bread",
        "source": "url",
        "lookup_field": "pk",
        "url_source": "url",
        "select_related": ["image"],
    },
    "basket": {
        "label": "Bread basket",
        "model": "blog.Bread",
        "source": "blog.actions.basket_items",
    },
    "basket_count": {
        "label": "Basket item count",
        "model": "blog.Bread",
        "source": "blog.actions.basket_count",
    },
}

# Developer-defined actions used by Action buttons.
WAGTAIL_DAISIE_ACTIONS = {
    "basket.add": {
        "label": "Add to basket",
        "handler": "blog.actions.basket_add",
    },
    "basket.remove": {
        "label": "Remove from basket",
        "handler": "blog.actions.basket_remove",
    },
    "basket.clear": {
        "label": "Clear basket",
        "handler": "blog.actions.basket_clear",
    },
}

# Audiences: request rules plus an optional queryset for campaigns.
WAGTAIL_DAISIE_AUDIENCE_RULES = {
    "staff": {
        "label": "Staff members",
        "rule": "blog.audience.is_staff",
        "queryset": "blog.audience.staff_users",
    },
    "newsletter": {
        "label": "Newsletter subscribers",
        "rule": "blog.audience.has_newsletter",
    },
}

# Notification bridges: email the Newsletter audience when a blog post publishes.
WAGTAIL_DAISIE_NOTIFICATION_BRIDGES = {
    "blog_post_published": {
        "label": "Blog post published",
        "template": "Blog post published",
        "signal": "wagtail.signals.page_published",
        "sender": "blog.BlogPage",
        "context": "blog.notifications.blog_post_context",
        "recipients": "blog.notifications.newsletter_recipients",
        "placeholders": {
            "title": "The published post title",
            "url": "The published post URL",
        },
    },
}

# DaisyUI styling for the allauth account pages and forms.
WAGTAIL_DAISIE_ALLAUTH_UI = True

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_ADAPTER = "demo.adapters.AccountAdapter"
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_LOGOUT_ON_GET = True
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
