# Generated by Django 6.0.4 on 2026-06-10 12:48

import colorfield.fields
import django.db.models.deletion
import modelcluster.fields
import wagtail.models.preview
import wagtail_daisIE.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaisyUITheme',
            fields=[
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('default', models.BooleanField(default=False, help_text='Is this the default theme?', verbose_name='Set as default')),
                ('prefers_dark', models.BooleanField(default=False, help_text='Is this the default dark theme?', verbose_name='Set as default dark theme')),
                ('color_scheme', models.CharField(choices=[('normal', 'Normal'), ('light', 'Light'), ('dark', 'Dark')], default='light', help_text='This theme will be applied to browsers with this color scheme', max_length=128, verbose_name='Color scheme')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
            ],
            options={
                'verbose_name': 'DaisyUI Theme',
                'verbose_name_plural': 'DaisyUI Themes',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DaisyUIThemeColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', colorfield.fields.ColorField(default='#422ad5ff', help_text='The main color of your theme', image_field=None, max_length=25, samples=None, verbose_name='Primary theme color')),
                ('primary_content', colorfield.fields.ColorField(default='#e0e7ffff', help_text='Foreground content color to use on primary color', image_field=None, max_length=25, samples=None, verbose_name='Primary theme content color')),
                ('secondary', colorfield.fields.ColorField(default='#f43098ff', help_text='The secondary color of your theme', image_field=None, max_length=25, samples=None, verbose_name='Secondary theme color')),
                ('secondary_content', colorfield.fields.ColorField(default='#f9e4f0ff', help_text='Foreground content color to use on secondary color', image_field=None, max_length=25, samples=None, verbose_name='Secondary theme content color')),
                ('accent', colorfield.fields.ColorField(default='#00d3bbff', help_text='The accent color of your theme', image_field=None, max_length=25, samples=None, verbose_name='Accent theme color')),
                ('accent_content', colorfield.fields.ColorField(default='#084d49ff', help_text='Foreground content color to use on accent color', image_field=None, max_length=25, samples=None, verbose_name='Accent theme content color')),
                ('neutral', colorfield.fields.ColorField(default='#0b0809ff', help_text='For not-saturated parts of UI', image_field=None, max_length=25, samples=None, verbose_name='Neutral dark color')),
                ('neutral_content', colorfield.fields.ColorField(default='#e7e3e4ff', help_text='Foreground content color to use on neutral color', image_field=None, max_length=25, samples=None, verbose_name='Neutral dark content color')),
                ('base_100', colorfield.fields.ColorField(default='#ffffffff', help_text='Used for blank backgrounds', image_field=None, max_length=25, samples=None, verbose_name='Base surface color of page')),
                ('base_200', colorfield.fields.ColorField(default='##f8f8f8ff', help_text='To create elevations', image_field=None, max_length=25, samples=None, verbose_name='Base color, darker shade')),
                ('base_300', colorfield.fields.ColorField(default='#eeeeeeff', help_text='To create elevations', image_field=None, max_length=25, samples=None, verbose_name='Base color, even darker shade')),
                ('base_content', colorfield.fields.ColorField(default='#1b1718ff', help_text='Foreground content color to use on base color', image_field=None, max_length=25, samples=None, verbose_name='Base content color')),
                ('info', colorfield.fields.ColorField(default='#00bafeff', help_text='For informative/helpful messages', image_field=None, max_length=25, samples=None, verbose_name='Info color')),
                ('info_content', colorfield.fields.ColorField(default='#042e49ff', help_text='Foreground content color to use on info color', image_field=None, max_length=25, samples=None, verbose_name='Info content color')),
                ('success', colorfield.fields.ColorField(default='#00d390ff', help_text='For success/safe messages', image_field=None, max_length=25, samples=None, verbose_name='Success color')),
                ('success_content', colorfield.fields.ColorField(default='#004c39ff', help_text='Foreground content color to use on success color', image_field=None, max_length=25, samples=None, verbose_name='Success content color')),
                ('warning', colorfield.fields.ColorField(default='#fcb700ff', help_text='For warning/caution messages', image_field=None, max_length=25, samples=None, verbose_name='Warning color')),
                ('warning_content', colorfield.fields.ColorField(default='#793205ff', help_text='Foreground content color to use on warning color', image_field=None, max_length=25, samples=None, verbose_name='Warning content color')),
                ('error', colorfield.fields.ColorField(default='#ff637dff', help_text='For error/danger/destructive messages', image_field=None, max_length=25, samples=None, verbose_name='Error color')),
                ('error_content', colorfield.fields.ColorField(default='#4d0218ff', help_text='Foreground content color to use on error color', image_field=None, max_length=25, samples=None, verbose_name='Error content color')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='wagtail_daisIE.daisyuitheme', unique=True)),
            ],
            options={
                'verbose_name': 'DaisyUI Theme Colors',
                'verbose_name_plural': 'DaisyUI Theme Colors',
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeEffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.BooleanField(default=True, help_text='Add 3D depth on fields & selectors', verbose_name='Depth effect')),
                ('noise', models.BooleanField(default=False, help_text='Add noise pattern on fields & selectors', verbose_name='Noise effect')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='wagtail_daisIE.daisyuitheme', unique=True)),
            ],
            options={
                'verbose_name': 'DaisyUI Theme Effects',
                'verbose_name_plural': 'DaisyUI Theme Effects',
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeRadii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', wagtail_daisIE.models.DaisyUISizeField(default='0.5rem', help_text='For card, modal, alert UI', verbose_name='Box border radius')),
                ('field', wagtail_daisIE.models.DaisyUISizeField(default='0.25rem', help_text='For button, input, select, tab UI', verbose_name='Field border radius')),
                ('selector', wagtail_daisIE.models.DaisyUISizeField(default='1rem', help_text='For checkbox, toggle, badge UI', verbose_name='Selector border radius')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='radii', to='wagtail_daisIE.daisyuitheme', unique=True)),
            ],
            options={
                'verbose_name': 'DaisyUI Theme Border Radii',
                'verbose_name_plural': 'DaisyUI Theme Border Radii',
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', wagtail_daisIE.models.DaisyUISizeField(default='0.25rem', help_text='For button, input, select, tab UI', verbose_name='Field base size')),
                ('selector', wagtail_daisIE.models.DaisyUISizeField(default='0.25rem', help_text='For checkbox, toggle, badge UI', verbose_name='Selector base size')),
                ('border', wagtail_daisIE.models.DaisyUISizeField(default='1px', help_text='For all elements', verbose_name='Border width')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='wagtail_daisIE.daisyuitheme', unique=True)),
            ],
            options={
                'verbose_name': 'DaisyUI Theme Sizes',
                'verbose_name_plural': 'DaisyUI Theme Sizes',
            },
        ),
        migrations.AddConstraint(
            model_name='daisyuitheme',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('default',), name='wagtail_daisIE.unique_default_theme'),
        ),
        migrations.AddConstraint(
            model_name='daisyuitheme',
            constraint=models.UniqueConstraint(condition=models.Q(('prefers_dark', True)), fields=('prefers_dark',), name='wagtail_daisIE.unique_default_dark_theme'),
        ),
    ]
