# Generated by Django 6.1.1 on 2026-10-04 07:03

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.models.preview
import wagtail_daisIE.choicelist
import wagtail_daisIE.models.background
import wagtail_daisIE.models.fields
import wagtail_daisIE.models.fonts
import wagtail_daisIE.models.theme
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaisyUIThemeFontFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(choices=wagtail_daisIE.models.fonts.font_family_role_choices, default='body', help_text='The font family is used for what? Headings, body text, code, or a custom stack.', max_length=16, verbose_name='Role')),
                ('name', models.SlugField(blank=True, help_text="Identifier for custom fonts, used in CSS variables. E.g. 'display' becomes --font-display.Required for custom fonts.", max_length=255, verbose_name='Name')),
                ('font_family', models.CharField(default='Inter', help_text='Primary font family name, e.g. Inter.', max_length=255, verbose_name='Font family name')),
                ('generic_font_family', models.CharField(choices=wagtail_daisIE.models.fonts.generic_font_family_choices, default='sans-serif', help_text='Browser-provided font used as the last resort if none of the fonts above are available.', max_length=255, verbose_name='Generic font family')),
                ('url', models.URLField(blank=True, help_text="Full URL to this font's stylesheet (e.g. Google Fonts link tag href).For use in email templates.Leave blank if this is a web-safe font or not used in an email template.", verbose_name='Font CDN URL')),
            ],
        ),
        migrations.CreateModel(
            name='DaisyUITheme',
            fields=[
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('default', models.BooleanField(default=False, help_text='Is this the default theme?', verbose_name='Set as default')),
                ('prefers_dark', models.BooleanField(default=False, help_text='Is this the default dark theme?', verbose_name='Set as default dark theme')),
                ('color_scheme', models.CharField(choices=wagtail_daisIE.models.theme.color_scheme_choices, default='light', help_text='This theme will be applied to browsers with this color scheme', max_length=128, verbose_name='Color scheme')),
                ('main_design', wagtail.fields.StreamField([('main', 48)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('MAIN_LAYOUT_CHOICES')}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BLOCK_SIZE_CHOICES'), 'help_text': 'Size for block elements.', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BLOCK_WIDTH_CHOICES'), 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BLOCK_MIN_WIDTH_CHOICES'), 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BLOCK_MAX_WIDTH_CHOICES'), 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('width', 2), ('min_width', 3), ('max_width', 4)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BLOCK_HEIGHT_CHOICES'), 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BLOCK_MIN_HEIGHT_CHOICES'), 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BLOCK_MAX_HEIGHT_CHOICES'), 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('height', 6), ('min_height', 7), ('max_height', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('size', 1), ('width', 5), ('height', 9)]], {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('GAP_ALL_CHOICES'), 'help_text': 'Spacing for all sides.', 'label': 'Spacing', 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('GAP_HORIZONTAL_CHOICES'), 'help_text': 'Spacing for horizontal sides.', 'label': 'Horizontal Spacing', 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('GAP_VERTICAL_CHOICES'), 'help_text': 'Spacing for vertical sides.', 'label': 'Vertical Spacing', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('all', 11), ('horizontal', 12), ('vertical', 13)]], {}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BACKGROUND_LAYER_TYPE_CHOICES'), 'classname': 'background-layer-form', 'max_length': 10, 'verbose_name': 'Layer type'}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('DAISYUI_BG_COLOR_CHOICES'), 'classname': 'layer-solid', 'label': 'Background color', 'required': False}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'form_classname': 'layer-image', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'center', 'form_classname': 'layer-image', 'help_text': 'CSS background-position, e.g. center, 50%, 10px.', 'max_length': 64, 'required': False, 'verbose_name': 'Position'}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BACKGROUND_SIZE_CHOICES'), 'classname': 'layer-image', 'max_length': 64, 'verbose_name': 'Size'}), 20: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'form_classname': 'layer-image', 'required': False, 'verbose_name': 'Repeat'}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('GRADIENT_SHAPE_CHOICES'), 'classname': 'layer-gradient', 'help_text': "e.g. 'linear', 'radial', 'conic'", 'max_length': 64, 'required': False, 'verbose_name': 'Gradient shape'}), 22: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'form_classname': 'layer-gradient', 'help_text': 'e.g. 0, 90, 180, 270', 'max_value': 360, 'min_value': 0, 'required': False, 'verbose_name': 'Gradient angle'}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('DAISYUI_BG_COLOR_CHOICES'), 'label': 'Background color', 'required': False}), 24: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': "e.g. '0%' or '100%'", 'max_value': 100, 'min_value': 0, 'required': False, 'verbose_name': 'Position'}), 25: ('wagtail.blocks.StructBlock', [[('bg_color', 23), ('position', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'form_classname': 'layer-gradient', 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('layer_type', 15), ('color', 16), ('image', 17), ('position', 18), ('size', 19), ('repeat', 20), ('gradient_shape', 21), ('gradient_angle', 22), ('gradient_stops', 26)]], {}), 28: ('wagtail.blocks.StreamBlock', [[('layer', 27)]], {'required': False}), 29: ('wagtail.blocks.IntegerBlock', (), {'default': None, 'help_text': 'Border width in pixels.', 'max_value': 999, 'required': False}), 30: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('DAISYUI_BORDER_COLOR_CHOICES'), 'required': False}), 31: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('BORDER_STYLE_CHOICES'), 'required': False}), 32: ('wagtail.blocks.StructBlock', [[('border_width', 29), ('border_color', 30), ('border_style', 31)]], {}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('PADDING_ALL_CHOICES'), 'help_text': 'Padding for all sides.', 'required': False}), 34: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('PADDING_TOP_CHOICES'), 'label': 'Top Padding', 'required': False}), 35: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('PADDING_RIGHT_CHOICES'), 'label': 'Right Padding', 'required': False}), 36: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('PADDING_BOTTOM_CHOICES'), 'label': 'Bottom Padding', 'required': False}), 37: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('PADDING_LEFT_CHOICES'), 'label': 'Left Padding', 'required': False}), 38: ('wagtail.blocks.StructBlock', [[('all_padding', 33), ('top', 34), ('right', 35), ('bottom', 36), ('left', 37)]], {}), 39: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('MARGIN_ALL_CHOICES'), 'help_text': 'Margin for all sides.', 'required': False}), 40: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('MARGIN_TOP_CHOICES'), 'label': 'Top Margin', 'required': False}), 41: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('MARGIN_RIGHT_CHOICES'), 'label': 'Right Margin', 'required': False}), 42: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('MARGIN_BOTTOM_CHOICES'), 'label': 'Bottom Margin', 'required': False}), 43: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('MARGIN_LEFT_CHOICES'), 'label': 'Left Margin', 'required': False}), 44: ('wagtail.blocks.StructBlock', [[('all_margins', 39), ('top', 40), ('right', 41), ('bottom', 42), ('left', 43)]], {}), 45: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('ROUNDED_CHOICES'), 'label': 'Rounded corners', 'required': False}), 46: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.choicelist.get_choice_list('SHADOW_CHOICES'), 'required': False}), 47: ('wagtail.blocks.StructBlock', [[('rounded', 45), ('shadow', 46)]], {}), 48: ('wagtail.blocks.StructBlock', [[('layout', 0), ('size', 10), ('spacing', 14), ('background', 28), ('border', 32), ('padding', 38), ('margin', 44), ('box', 47)]], {})}, default=[], help_text='Design the main content container.', verbose_name='Main design')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
            ],
            options={
                'verbose_name': 'DaisyUI Theme',
                'verbose_name_plural': 'DaisyUI Themes',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DaisyUIThemeBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='background', to='wagtail_daisIE.daisyuitheme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeBackgroundLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('layer_type', models.CharField(choices=wagtail_daisIE.models.background.layer_type_choices, default='solid', max_length=10, verbose_name='Layer type')),
                ('color', wagtail_daisIE.models.fields.DaisyUIColorField(blank=True, default=None, help_text='Pick a colour from the theme palette or choose any custom colour.', image_field=None, max_length=25, null=True, samples=None, verbose_name='Colour')),
                ('gradient_shape', models.CharField(blank=True, default='linear-gradient', help_text="e.g. 'linear', 'radial', 'conic'", max_length=64, verbose_name='Gradient shape')),
                ('gradient_angle', models.PositiveSmallIntegerField(blank=True, default=0, help_text='e.g. 0, 90, 180, 270', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Gradient angle')),
                ('position', models.CharField(blank=True, default='center', help_text='CSS background-position, e.g. center, 50%, 10px.', max_length=64, verbose_name='Position')),
                ('size', models.CharField(choices=wagtail_daisIE.models.background.background_size_choices, default='cover', max_length=64, verbose_name='Size')),
                ('repeat', models.BooleanField(default=False, verbose_name='Repeat')),
                ('background', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='wagtail_daisIE.daisyuithemebackground')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeBackgroundLayerGradientStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('color', wagtail_daisIE.models.fields.DaisyUIColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Colour')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=0, help_text="e.g. '0%' or '100%'", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Position')),
                ('layer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='wagtail_daisIE.daisyuithemebackgroundlayer')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('primary', wagtail_daisIE.models.fields.DaisyUIColorField(default='#422ad5ff', help_text='The main color of your theme', image_field=None, max_length=25, samples=None, verbose_name='Primary theme color')),
                ('primary_content', wagtail_daisIE.models.fields.DaisyUIColorField(default='#e0e7ffff', help_text='Foreground content color to use on primary color', image_field=None, max_length=25, samples=None, verbose_name='Primary theme content color')),
                ('secondary', wagtail_daisIE.models.fields.DaisyUIColorField(default='#f43098ff', help_text='The secondary color of your theme', image_field=None, max_length=25, samples=None, verbose_name='Secondary theme color')),
                ('secondary_content', wagtail_daisIE.models.fields.DaisyUIColorField(default='#f9e4f0ff', help_text='Foreground content color to use on secondary color', image_field=None, max_length=25, samples=None, verbose_name='Secondary theme content color')),
                ('accent', wagtail_daisIE.models.fields.DaisyUIColorField(default='#00d3bbff', help_text='The accent color of your theme', image_field=None, max_length=25, samples=None, verbose_name='Accent theme color')),
                ('accent_content', wagtail_daisIE.models.fields.DaisyUIColorField(default='#084d49ff', help_text='Foreground content color to use on accent color', image_field=None, max_length=25, samples=None, verbose_name='Accent theme content color')),
                ('neutral', wagtail_daisIE.models.fields.DaisyUIColorField(default='#0b0809ff', help_text='For not-saturated parts of UI', image_field=None, max_length=25, samples=None, verbose_name='Neutral dark color')),
                ('neutral_content', wagtail_daisIE.models.fields.DaisyUIColorField(default='#e7e3e4ff', help_text='Foreground content color to use on neutral color', image_field=None, max_length=25, samples=None, verbose_name='Neutral dark content color')),
                ('base_100', wagtail_daisIE.models.fields.DaisyUIColorField(default='#ffffffff', help_text='Used for blank backgrounds', image_field=None, max_length=25, samples=None, verbose_name='Base surface color of page')),
                ('base_200', wagtail_daisIE.models.fields.DaisyUIColorField(default='#f8f8f8ff', help_text='To create elevations', image_field=None, max_length=25, samples=None, verbose_name='Base color, darker shade')),
                ('base_300', wagtail_daisIE.models.fields.DaisyUIColorField(default='#eeeeeeff', help_text='To create elevations', image_field=None, max_length=25, samples=None, verbose_name='Base color, even darker shade')),
                ('base_content', wagtail_daisIE.models.fields.DaisyUIColorField(default='#1b1718ff', help_text='Foreground content color to use on base color', image_field=None, max_length=25, samples=None, verbose_name='Base content color')),
                ('info', wagtail_daisIE.models.fields.DaisyUIColorField(default='#00bafeff', help_text='For informative/helpful messages', image_field=None, max_length=25, samples=None, verbose_name='Info color')),
                ('info_content', wagtail_daisIE.models.fields.DaisyUIColorField(default='#042e49ff', help_text='Foreground content color to use on info color', image_field=None, max_length=25, samples=None, verbose_name='Info content color')),
                ('success', wagtail_daisIE.models.fields.DaisyUIColorField(default='#00d390ff', help_text='For success/safe messages', image_field=None, max_length=25, samples=None, verbose_name='Success color')),
                ('success_content', wagtail_daisIE.models.fields.DaisyUIColorField(default='#004c39ff', help_text='Foreground content color to use on success color', image_field=None, max_length=25, samples=None, verbose_name='Success content color')),
                ('warning', wagtail_daisIE.models.fields.DaisyUIColorField(default='#fcb700ff', help_text='For warning/caution messages', image_field=None, max_length=25, samples=None, verbose_name='Warning color')),
                ('warning_content', wagtail_daisIE.models.fields.DaisyUIColorField(default='#793205ff', help_text='Foreground content color to use on warning color', image_field=None, max_length=25, samples=None, verbose_name='Warning content color')),
                ('error', wagtail_daisIE.models.fields.DaisyUIColorField(default='#ff637dff', help_text='For error/danger/destructive messages', image_field=None, max_length=25, samples=None, verbose_name='Error color')),
                ('error_content', wagtail_daisIE.models.fields.DaisyUIColorField(default='#4d0218ff', help_text='Foreground content color to use on error color', image_field=None, max_length=25, samples=None, verbose_name='Error content color')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='wagtail_daisIE.daisyuitheme')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeEffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('depth', models.BooleanField(default=True, help_text='Add 3D depth on fields & selectors', verbose_name='Depth effect')),
                ('noise', models.BooleanField(default=False, help_text='Add noise pattern on fields & selectors', verbose_name='Noise effect')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='wagtail_daisIE.daisyuitheme')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeFontCDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('url', models.URLField(help_text='Full URL to a font stylesheet (e.g. Google Fonts link tag href)', verbose_name='Font CDN URL')),
                ('label', models.CharField(blank=True, help_text='Optional label to identify this CDN link', max_length=255, verbose_name='Label')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_cdns', to='wagtail_daisIE.daisyuitheme')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeFontFallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Font family name for the fallback font, e.g. Roboto.', max_length=255, verbose_name='Font family name')),
                ('font_family', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallbacks', to='wagtail_daisIE.daisyuithemefontfamily')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeFonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('base_font_size', wagtail_daisIE.models.fields.DaisyUISizeField(default='1rem', help_text='Base font size for body text', verbose_name='Base font size')),
                ('line_height', models.FloatField(default=1.5, help_text='Line height multiplier for body text', verbose_name='Line height')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='wagtail_daisIE.daisyuitheme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='daisyuithemefontfamily',
            name='fonts',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_families', to='wagtail_daisIE.daisyuithemefonts'),
        ),
        migrations.CreateModel(
            name='DaisyUIThemeRadii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('box', wagtail_daisIE.models.fields.DaisyUISizeField(default='0.5rem', help_text='For card, modal, alert UI', verbose_name='Box border radius')),
                ('field', wagtail_daisIE.models.fields.DaisyUISizeField(default='0.25rem', help_text='For button, input, select, tab UI', verbose_name='Field border radius')),
                ('selector', wagtail_daisIE.models.fields.DaisyUISizeField(default='1rem', help_text='For checkbox, toggle, badge UI', verbose_name='Selector border radius')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='radii', to='wagtail_daisIE.daisyuitheme')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DaisyUIThemeSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('field', wagtail_daisIE.models.fields.DaisyUISizeField(default='0.25rem', help_text='For button, input, select, tab UI', verbose_name='Field base size')),
                ('selector', wagtail_daisIE.models.fields.DaisyUISizeField(default='0.25rem', help_text='For checkbox, toggle, badge UI', verbose_name='Selector base size')),
                ('border', wagtail_daisIE.models.fields.DaisyUISizeField(default='1px', help_text='For all elements', verbose_name='Border width')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='wagtail_daisIE.daisyuitheme')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='daisyuitheme',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('default',), name='wagtail_daisIE.unique_default_theme'),
        ),
        migrations.AddConstraint(
            model_name='daisyuitheme',
            constraint=models.UniqueConstraint(condition=models.Q(('prefers_dark', True)), fields=('prefers_dark',), name='wagtail_daisIE.unique_default_dark_theme'),
        ),
        migrations.AddConstraint(
            model_name='daisyuithemefontfamily',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['heading', 'body', 'subheading', 'code'])), fields=('fonts', 'role'), name='wagtail_daisIE.unique_font_family_role'),
        ),
        migrations.AddConstraint(
            model_name='daisyuithemefontfamily',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'custom')), fields=('fonts', 'name'), name='wagtail_daisIE.unique_font_family_name'),
        ),
        migrations.AddConstraint(
            model_name='daisyuithemefontfamily',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'custom'), _negated=True), models.Q(('name', ''), _negated=True), _connector='OR'), name='wagtail_daisIE.check_font_family_name'),
        ),
    ]
