# Generated by Django 6.1.1 on 2026-09-26 20:24

import wagtail.fields
import wagtail_daisIE.dynamic.registry
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_daisIE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daisyuimenu',
            name='context_bindings',
            field=wagtail.fields.StreamField([('binding', 7)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': wagtail_daisIE.dynamic.registry.get_context_model_choices, 'help_text': 'The variable content can reference, e.g. {{ meeting }}.', 'label': 'Value'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('automatic', 'Automatic'), ('url', 'From the URL'), ('fixed', 'Specific instance')], 'label': 'Source', 'required': False}), 2: ('wagtail_daisIE.dynamic.blocks.DynamicInstanceChooserBlock', (), {'label': 'Instance', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('path', 'Path parameter'), ('query', 'Query parameter')], 'help_text': 'Where in the request URL the value is read from.', 'label': 'Read from', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'The URL parameter to look up (defaults to the model config).', 'label': 'Parameter name', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Optional regular expression the value must fully match, e.g. [\\w-]+.', 'label': 'Value pattern', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Shown when the value cannot be resolved (e.g. no signed-in user).', 'label': 'Fallback', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('key', 0), ('mode', 1), ('object_id', 2), ('lookup_in', 3), ('lookup_field', 4), ('lookup_pattern', 5), ('fallback', 6)]], {})}, help_text="Expose context models to this menu's items, e.g. the current user.", verbose_name='Context bindings'),
        ),
    ]
