# Generated by Django 6.1.1 on 2026-09-26 20:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_daisIE', '0002_alter_daisyuimenu_context_bindings'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaisyUIFavicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=128, verbose_name='App name')),
                ('short_name', models.CharField(blank=True, max_length=64, verbose_name='Short name')),
                ('theme_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$', 'Enter a hex colour such as #A1B2C3.')], verbose_name='Theme colour')),
                ('background_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$', 'Enter a hex colour such as #A1B2C3.')], verbose_name='Background colour')),
                ('display', models.CharField(blank=True, choices=[('standalone', 'Standalone'), ('minimal-ui', 'Minimal UI'), ('fullscreen', 'Fullscreen'), ('browser', 'Browser')], default='standalone', max_length=16, verbose_name='Display')),
                ('image', models.ForeignKey(blank=True, help_text='A square, transparent PNG at least 1024x1024 works best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon image')),
                ('site', models.ForeignKey(blank=True, help_text='Leave blank to use this favicon as the default for all sites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicons',
                'constraints': [models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('site',), name='wagtail_daisIE_unique_favicon_site'), models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('site',), name='wagtail_daisIE_unique_favicon_default')],
            },
        ),
    ]
