# Generated by Django 6.1.1 on 2026-10-04 07:03

import django.db.models.deletion
import wagtail_daisIE.assets.models
import wagtail_daisIE.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaisyUIIconSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Name shown in the icon picker.', max_length=255, verbose_name='Label')),
                ('prefix', models.SlugField(help_text="Unique identifier used before the colon, e.g. 'mdi' in 'mdi:home'.", max_length=64, unique=True, verbose_name='Prefix')),
                ('provider', models.CharField(choices=wagtail_daisIE.assets.models.icon_provider_choices, default='iconify', max_length=16, verbose_name='Provider')),
                ('enabled', models.BooleanField(default=True, help_text='Show this source in the icon picker.', verbose_name='Enabled')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order')),
                ('api_base', models.URLField(blank=True, help_text='Leave blank to use the configured default Iconify API.', verbose_name='Iconify API base URL')),
                ('css_url', models.URLField(blank=True, help_text='Stylesheet that provides the icon font classes.', verbose_name='Web font CSS URL')),
                ('css_class_prefix', models.CharField(blank=True, help_text="Prefix added to the icon name, e.g. 'fa-solid fa-'.", max_length=64, verbose_name='Class prefix')),
                ('manifest_path', models.CharField(blank=True, help_text='Filesystem path to an IconifyJSON or name-to-SVG manifest.', max_length=255, verbose_name='Manifest path')),
                ('search_enabled', models.BooleanField(default=True, help_text='Allow searching this source in the picker.', verbose_name='Searchable')),
                ('info', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Cached metadata')),
            ],
            options={
                'verbose_name': 'DaisyUI Icon Source',
                'verbose_name_plural': 'DaisyUI Icon Sources',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DaisyUIFavicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=128, verbose_name='App name')),
                ('short_name', models.CharField(blank=True, max_length=64, verbose_name='Short name')),
                ('theme_color', wagtail_daisIE.models.fields.DaisyUIColorField(default='#FFFFFF', help_text='Hex or hexa colour, e.g. #A1B2C3 or #A1B2C3FF.', image_field=None, max_length=25, samples=None, verbose_name='Theme colour')),
                ('background_color', wagtail_daisIE.models.fields.DaisyUIColorField(default='#FFFFFF', help_text='Hex or hexa colour, e.g. #A1B2C3 or #A1B2C3FF.', image_field=None, max_length=25, samples=None, verbose_name='Background colour')),
                ('display', models.CharField(blank=True, choices=wagtail_daisIE.assets.models.favicon_display_choices, default='standalone', max_length=16, verbose_name='Display')),
                ('image', models.ForeignKey(blank=True, help_text='A square, transparent PNG at least 1024x1024 works best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon image')),
                ('site', models.ForeignKey(blank=True, help_text='Leave blank to use this favicon as the default for all sites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicons',
                'constraints': [models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('site',), name='wagtail_daisIE_unique_favicon_site'), models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('site',), name='wagtail_daisIE_unique_favicon_default')],
            },
        ),
    ]
